### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by sergiopvilar** [sntran/trello-broker#3]
Hello, I don't know nothing about python but I would like to use this tool. How can I install this?

Thanks!

**Comment by axelson** [comment]
+1

**Comment by shuvomahamud** [comment]
I have the same question how to install it please help!!!
Thanks

**Comment by sntran** [comment]
You can really "install" this, as this is (or used to be) a BitBucket broker. Now it is called service and then changed to [webhook](https://confluence.atlassian.com/bitbucket/manage-bitbucket-cloud-services-221449732.html), but it will need to be installed by BitBucket team. They don't accept new broker though, so this repo is pretty much obsolete.

You can find BitBucket hooks for Trello, such as https://github.com/olebedev/hook-to-trello or https://github.com/ricwa230/bitbucket-trello-hook.

**Comment by sntran** [comment]
Trello now has [official support for BitBucket](http://blog.trello.com/trello-power-ups-for-jira-bitbucket-confluence-hipchat)
